services:
 zookeeper:
   image: confluentinc/cp-zookeeper:latest
   container_name: zookeeper
   environment:
     ZOOKEEPER_CLIENT_PORT: "${ZOOKEEPER_PORT}"
     ZOOKEEPER_TICK_TIME: 2000
     TZ: "America/Bogota"
   ports:
     - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
   networks:
     - mynetwork
 kafka:
   image: confluentinc/cp-kafka:latest
   container_name: kafka
   depends_on:
     - zookeeper
   ports:
     - "${KAFKA_INSIDE_PORT}:${KAFKA_INSIDE_PORT}"
     - "${KAFKA_OUTSIDE_PORT}:${KAFKA_OUTSIDE_PORT}"
   environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:${KAFKA_INSIDE_PORT},OUTSIDE://localhost:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:${KAFKA_INSIDE_PORT},OUTSIDE://0.0.0.0:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      TZ: "America/Bogota" 
   networks:
     - mynetwork
 mongodb:
  image: mongo:latest
  container_name: mongodb
  ports:
    - "${MONGODB_OUTSIDE_PORT}:${MONGODB_INSIDE_PORT}"
  volumes:
    - mongodb_data:/data/db
  environment:
     TZ: "America/Bogota"  
  networks:
    - mynetwork

 api:
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - TCP_PORT=${TCP_INSIDE_PORT}  # Pasar el puerto interno del contenedor
  container_name: tcp-api
  ports:
    - "${TCP_OUTSIDE_PORT}:${TCP_INSIDE_PORT}"  # Mapeo correcto
  environment:
    ASPNETCORE_ENVIRONMENT: "Development"
    Kafka__BootstrapServers: "kafka:${KAFKA_INSIDE_PORT}"
    TCP__Port: ${TCP_INSIDE_PORT}  # Cambiar para que coincida con el puerto interno
    TZ: "America/Bogota"
  networks:
    - mynetwork
networks:
 mynetwork:
   driver: bridge
volumes:
 mongodb_data: