services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mynetwork

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TCP_PORT=${TCP_PORT}
    container_name: tcp-api
    ports:
      - "${TCP_PORT}:${TCP_PORT}"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      Kafka__BootstrapServers: "kafka:9092"
      TCP__Port: ${TCP_PORT}
    networks:
      - mynetwork                   # Override de puerto TCP

networks:
  mynetwork:
    driver: bridge
